In [1]:
import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [6]:
math.ceil(7.8)

8

In [7]:
math.ceil(2.4)

3

In [8]:
float_list = [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]

In [9]:
sum(float_list)

0.7

In [10]:
math.fsum(float_list)

0.7000000000000001

In [11]:
pip install numpy

You should consider upgrading via the '/Users/macintoshhd/Public/Project/Learn/ML/ml_env/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [12]:
import numpy as np

In [13]:
some_list = [1, 2, 3, 4, 5, 6, 7]
type(some_list)

list

In [14]:
some_array = np.array(some_list)
type(some_array)

numpy.ndarray

In [15]:
some_array

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
ones_array = np.ones(6)
ones_array

array([1., 1., 1., 1., 1., 1.])

In [20]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [21]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
reshaped_array = range_array.reshape(4,2)
reshaped_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [25]:
random_array = np.random.random((4, 5))
random_array

array([[0.55072348, 0.89358146, 0.38900716, 0.98091673, 0.3165054 ],
       [0.51785765, 0.96322795, 0.13950419, 0.28982318, 0.60369262],
       [0.30081067, 0.81841973, 0.60711207, 0.52275904, 0.57219522],
       [0.99606677, 0.69039734, 0.73585334, 0.30955316, 0.30204389]])

In [26]:
mean = np.mean(range_array)
mean

3.5

In [27]:
median = np.median(range_array)
median

3.5

In [28]:
var = np.var(range_array)
var

5.25

In [29]:
std = np.std(range_array)
std

2.29128784747792

In [30]:
pip install pandas

You should consider upgrading via the '/Users/macintoshhd/Public/Project/Learn/ML/ml_env/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [31]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.
